// מילון תרגום נושאים (Themes) מאנגלית (כפי שנשמרים במאגר) לעברית לתצוגה
export const THEME_TRANSLATIONS = {
  "Obsession & Self-Destruction": "אובססיה והרס עצמי",
  "Alienation & Urban Isolation": "ניכור ובדידות עירונית",
  "Grief, Mourning & Loss": "אבל, שכול ואובדן",
  "Guilt, Remorse & Redemption": "אשמה, חרטה וכפרה",
  "Madness, Psychosis & Mental Collapse": "שגעון, פסיכוזה ואובדן שליטה",
  "Identity Crisis & Self-Discovery": "משבר זהות והגדרה עצמית",
  "Coming of Age & Loss of Innocence": "התבגרות וסוף התמימות",
  "Repression, Anxiety & Shame": "הדחקה, חרדה ובושה",
  "Marital Decay & Relationship Breakdown": "שחיקה זוגית ופירוק הנישואין",
  "Generational Divide & Parent-Child Conflict": "יחסי הורים-ילדים ופער דורות",
  "Dependency, Jealousy & Power Dynamics": "תלות, קנאה ומאבקי שליטה",
  "Desire, Carnal Lust & Degradation": "תשוקה, יצרים והשפלה גופנית",
  "Collapse of the Family Unit": "קריסת התא המשפחתי",
  "Immigration, Displacement & Exile": "הגירה, עקירה וזרות",
  "Social Class, Poverty & Exploitation": "מעמד, עוני וניצול כלכלי",
  "Institutional Corruption & Political Power": "שחיתות ממסדית ומשחקי כוח",
  "Systemic Violence & Organized Crime": "אלימות ממסדית ופשע מאורגן",
  "Conformism, Oppression & Suffocating Routine": "קונפורמיזם, דיכוי ושגרה מחנקת",
  "Moral Justice, Retribution & Crime": "צדק מוסרי, נקמה ופשע",
  "Existential Dread & Mortality": "חרדה קיומית ומפגש עם המוות",
  "Faith, Doubt & Spiritual Seeking": "אמונה, ספק וחיפוש רוחני",
  "The Absurd, Chance & Meaninglessness": "האבסורד, אקראיות וחוסר פשר",
  "Memory, Time & Oblivion": "זיכרון, זמן ושכחה",
  "Historical & Collective Trauma": "טראומה היסטורית וקולקטיבית",
  "Art, Creation & the Price of Genius": "אמנות, יצירה ומחיר הגאונות",
  "Moral Decay & Nihilism": "התפרקות מוסרית וניהיליזם",
  "Man vs. Nature & the Elements": "האדם מול הטבע והסביבה",
  "Illusion, Deception & Perceived Reality": "אשליה, זיוף ומציאות מדומה"
};
